<a href="https://colab.research.google.com/github/Manversajjad/Project_pandas/blob/main/Graded_project_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Session 2
## Graded Comprehension 1: IMDb Movies

You are given the following data for movies released between 1916 and 2016. You are expected to find interesting insights using Python. You can download the movie dataset from the following link.

[movies_IMDB_dataset.csv](https://drive.google.com/file/d/1qColINjV5_DZ2OrtK1E2hTrhapj898Mh/view?usp=sharing)

Each column of the dataset is explained below.
<br>

| Column Name | Description |
| :- |:-: |
| movie_title | Title of the movie |
| color | Whether the movie is in color or black and white |
| director_name | Name of the director |
| num_critic_for_reviews | Number of critic reviews for the movie |
| duration | Duration of the movie |
| director_facebook_likes | Number of likes on the director’s Facebook page |
| actor_3_facebook_likes | Number of likes on supporting actor 2’s Facebook page |
| actor_2_name | Name of supporting actor 1 |
| actor_1_facebook_likes | Number of likes on the main actor’s Facebook page |
| gross | Total earnings at the box office |
| genres | Genre of the movie (May be multiple genres separated by a '|'. The first one is the primary genre for the movie.) |
| actor_1_name | Name of the main actor |
| num_voted_users | Total number of votes/ratings |
| cast_total_facebook_likes | Total likes on the cast’s Facebook pages |
| actor_3_name | Name of supporting actor 2 |
| facenumber_in_poster | Number of faces on the poster |
| plot_keywords | Keywords for the plot |
| movie_imdb_link | Link to IMDb page listing for the movie |
| num_user_for_reviews | Total number of user reviews (text reviews) |
| language | Language in which the movie was originally shot |
| country | Country of origin for the movie production |
| content_rating | Age rating for the movie |
| budget | Budget required to make the movie |
| title_year | Year of release |
| actor_2_facebook_likes | Number of likes on the supporting actor’s Facebook page |
| imdb_score | IMDb score of the movie |
| aspect_ratio | Aspect ratio of the movie footage |
| movie_facebook_likes | Number of likes on the movie’s Facebook page |

<br>

You can use this Jupyter Notebook to answer the questions. You are expected to load the data into a DataFrame named **movies**.

In [5]:
import pandas as pd
import numpy as np

In [4]:
# Importing file from the location
importing_csv_file = pd.read_csv(r'/content/movies_IMDB_dataset.csv')
importing_csv_file.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
5,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
6,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
7,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
8,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
9,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000

**Question 1**: For this assignment, analyze features from the IMDb movie dataset. Exclude the following list of features from your analysis:
*   color
*   director_facebook_likes
*   actor_1_facebook_likes
*   actor_2_facebook_likes
*   actor_3_facebook_likes
*   actor_2_name
*   cast_total_facebook_likes
*   actor_3_name
*   duration
*   facenumber_in_poster
*   content_rating
*   country
*   movie_imdb_link
*   aspect_ratio
*   plot_keywords

<br>

Which of the following would you use to permanently drop the columns <code>["color", "director_facebook_likes", …"aspect_ratio", "plot_keywords"]</code> from the DataFrame **movies**?

A. movies.drop(["color", "director_facebook_likes", …"aspect_ratio", "plot_keywords"], inplace = True)\
B. movies.drop(["color", "director_facebook_likes", …"aspect_ratio", "plot_keywords"], axis = 1) \
C. movies.drop(["color", "director_facebook_likes", …"aspect_ratio", "plot_keywords"], axis = 1, inplace = True)\
D. movies.drop("color", "director_facebook_likes", …"aspect_ratio", "plot_keywords", axis = 1, inplace = True)

*List of columns to be dropped:*

['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio', 'plot_keywords']

In [70]:
# Write your code here
columns_to_drop = ['color', 'director_facebook_likes', 'actor_1_facebook_likes', 'actor_2_facebook_likes',
                   'actor_3_facebook_likes', 'actor_2_name', 'cast_total_facebook_likes', 'actor_3_name',
                   'duration', 'facenumber_in_poster', 'content_rating', 'country', 'movie_imdb_link',
                   'aspect_ratio', 'plot_keywords']

importing_csv_file.drop(columns=columns_to_drop, inplace=True)

In [71]:
importing_csv_file

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3848,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
3849,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
3850,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
3851,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
3852,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

**Question 2**: What is the total count of movies made in the English language?\
A. 3674 \
B. 3671 \
C. 3668 \
D. 3677

In [72]:
# Shape returns the actual number when the condition is being compared. We can also use value_count() function to get the same result
english_Language = importing_csv_file[importing_csv_file['language'] == 'English'].shape[0]
english_Language

3671

**Question 3**: Find the movie with the highest profit. Estimate a movie’s profit by subtracting the column 'budget' from the column 'gross'.<br>
**Hint:** You can add an additional column ‘profit’ to the DataFrame.

A.  *Titanic* \
B.  *Avatar* \
C.  *The Avengers* \
D.  *The Dark Knight*

In [30]:
# Write your code here
movies_profit = importing_csv_file['budget'] - importing_csv_file['gross']
importing_csv_file['profit'] = movies_profit
importing_csv_file['profit'].max()
importing_csv_file['movie_title']

0                                           Avatar
1         Pirates of the Caribbean: At World's End
2                                          Spectre
3                            The Dark Knight Rises
4                                      John Carter
                            ...
3849                                        Cavite
3850                                   El Mariachi
3851                                     Newlyweds
3852                             My Date with Drew
profit                                         NaN
Name: movie_title, Length: 3854, dtype: object

**Question 4**: What is the IMDb score for the movie ‘*The Dark Knight*’?

A.  7.9 \
B.  8.4 \
C.  9.0 \
D.  9.3

In [80]:
# Write your code here
Scoring_imdb = importing_csv_file[importing_csv_file['movie_title'] == 'The Dark Knight']
importing_csv_file['imdb_score']
Scoring_imdb

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
64,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000

**Question 5**: What is the average IMDb score for the movies starring Leonardo DiCaprio as the first actor?

A. 6.8 \
B. 7.3 \
C. 7.5 \
D. 8.2

In [7]:
# Write your code here
avg_score = importing_csv_file[importing_csv_file['actor_1_name'] == 'Leonardo DiCaprio']
avg_score['imdb_score'].mean()

7.495238095238095